name: tf-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - matplotlib==3.10.3
      - numpy==2.1.3
      - pandas==2.3.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - tensorflow==2.19.0
      - tensorflow-probability==0.25.0
      - spyder==6.0.7
      - imageio==2.37.0

